on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Runs Studio cli
    steps:
      - name: Hello world action step
        id: hello
        uses: shamik123/ShamikAction@shamiktestactionv5
        with:
          studio-cli-command: 'studio-cli --version'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
