on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Runs Studio cli
    steps:
      - name: Studio version check
        id: version
        uses: shamik123/ShamikAction@shamiktestactionv42
        env:
          MY_USER: "shamik.saha@windriver.com"
          MY_STUDIO: "https://feo-demo.wrstudio.cloud/"
          MY_PW: ${{ secrets.MY_PW }}
        with:
          studio-cli-command: 'studio-cli --version'
      - name: Show the output message
        run: echo "Output from command ${{ steps.version.outputs.message }}"
      - name: reserving virtual target
        id: virtual
        uses: shamik123/ShamikAction@shamiktestactionv42
          MY_USER: "shamik.saha@windriver.com"
          MY_STUDIO: "https://feo-demo.wrstudio.cloud/"
          MY_PW: ${{ secrets.MY_PW }}
        with:
          studio-cli-command: 'studio-cli vlab virtual reserve --id dcb2335c-a923-4605-a642-5cecff88e450 --hours 1 --var artifact_path=workspace-se/builds/michael-foglia/zcu_102_TEST/2403/vip -a'
      - name: Show the output message
        run: echo "Output from command ${{ steps.virtual.outputs.message }}"

      
        

 
