on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: Runs Studio cli
    steps:
      - name: Studio version check
        id: version
        uses: shamik123/ShamikAction@shamiktestaction48
        env:
          MY_USER: "shamik.saha@windriver.com"
          MY_STUDIO: "https://feo-demo.wrstudio.cloud/"
          MY_PW: ${{ secrets.MY_PW }}
        with:
          studio-cli-command: 'studio-cli --version'
      - name: Show the output message
        run: echo "Output from command ${{ steps.version.outputs.message }}"
      - name: reserving virtual target
        id: virtual
        uses: shamik123/ShamikAction@shamiktestaction48
        env:
          MY_USER: "shamik.saha@windriver.com"
          MY_STUDIO: "https://feo-demo.wrstudio.cloud/"
          MY_PW: ${{ secrets.MY_PW }}
        with:
          studio-cli-command: 'studio-cli vlab virtual reserve --id dcb2335c-a923-4605-a642-5cecff88e450 --hours 1 --var artifact_path=workspace-se/builds/michael-foglia/zcu_102_TEST/2403/vip -a'
      - name: Show the output message
        run: echo "Output from command ${{ steps.virtual.outputs.message }}"
      - name: Extract reservation ID
        run: |
          echo "Parsing ID from virtual reservation output..."
          
          # Isolate the JSON portion
          json_output=$(echo '${{ steps.virtual.outputs.message }}' | grep -o '{.*}' | sed 's/\\\"/\"/g')
          
          # Debug the extracted JSON
          echo "Extracted JSON: $json_output"
          
          # Check if valid JSON was extracted
          if [ -z "$json_output" ]; then
            echo "Error: No valid JSON found in the output."
            exit 1
          fi
          
          # Attempt to parse the ID
          id=$(echo "$json_output" | jq -r '.data.data.id // empty')
          
          # Debug the extracted ID
          echo "Extracted ID: $id"
          
          # Validate the extracted ID
          if [ -z "$id" ]; then
            echo "Error: Could not extract reservation ID."
            exit 1
          fi
          
          # Save to environment
          echo "reservation_id=$id" >> $GITHUB_ENV



      
        

 
