on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Runs Studio cli
    steps:
      - name: Hello world action step
        id: command
        uses: shamik123/ShamikAction@shamiktestaction32
        with:
          studio-cli-command: 'studio-cli --version'
      - name: Show the output message
        run: echo "Output from command ${{ steps.command.outputs.message }}"


        
