on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: Runs Studio cli
    env: # Environment variables at the job level
      MY_USER: "shamik.saha@windriver.com"
      MY_STUDIO: "https://feo-demo.wrstudio.cloud/"
      MY_PW: ${{ secrets.MY_PW }}
    steps:
      - name: reserving virtual target
        id: virtual
        uses: shamik123/ShamikAction@shamiktestaction52
        with:
          studio-cli-command: 'studio-cli vlab virtual reserve --id dcb2335c-a923-4605-a642-5cecff88e450 --hours 1 --var artifact_path=workspace-se/builds/michael-foglia/zcu_102_TEST/2403/vip -a --jq .data'
      - name: Show the output message
        run: echo "${{ steps.virtual.outputs.message }}"
      - name: Extract reservation ID
        id: extract_id
        run: |
          id=$(echo '${{ steps.virtual.outputs.message }}' | jq -r '.env')
          echo "Break"
          echo $id
      
